### ISSUE TITLE
Sometimes breaking on detaching on iOS

### ISSUE THREAD

**Issue by osdnk** [kmagiera/react-native-reanimated#112]
![image](https://user-images.githubusercontent.com/25709300/46571554-40305280-c977-11e8-921f-f27beb2fe207.png)
It appears sometimes, and is connected with calling callback on getting value during detaching. 
https://github.com/kmagiera/react-native-reanimated/commit/3bbf8a0fed9afeebe7987a21029fd7dc5fdc2038#diff-1ea1099449a3d9c97e383160f5a623e2R194
This line is breaking. 

Maybe it is an issue in RN. Is there ay reason, @kmagiera, you decided not to use callback in `call` node?

In order to repro e.g. navigate to "Interpolate" in Example app and then press back button

**Comment by bduyng** [comment]
I am getting this issue with Expo 31.0.0 which contains `react-native-reanimated 1.0.0-alpha.10. I just copy `MapPanel.js` and `Interactable.js` from `Example`

**Comment by osdnk** [comment]
Everyone,
This will be fixed in new version. Current workaround is just to make sure if there is no any `null` in `Value's. Nulls sending from Obj-C has to be wrapped into object which was done in related PR.
