### ISSUE TITLE
Spring animations are "slow" to end

### ISSUE THREAD

**Issue by wcandillon** [kmagiera/react-native-reanimated#132]
Thank you so much for making this great module. I started to build some video tutorial on how to use it:
* https://www.youtube.com/watch?v=vAtf1fENGDA
* https://www.youtube.com/watch?v=UbedXievYGI
* https://www.youtube.com/watch?v=8HYb6ixhLKQ

I've built a couple of animations using the runSpring function that we can find in the examples of the repo. You can find one here: https://snack.expo.io/@git/github.com/wcandillon/can-it-be-done-in-react-native:tinder-swiping (components/Profiles.js).
I have a condition on when the clock is stopped by the spring animation, this condition always evalutes much later (few seconds) after the animation is seemingly done. Is that a behavior that sound famillar or I would need to provide a smaller example?

**Comment by enesTufekci** [comment]
Hey @wcandillon, idk its the convenient way but maybe you can try to put a condition which checks the `clock` value is `lessThan` something then you can call the function? Thanks a lot for those great videos btw.

**Comment by wcandillon** [comment]
@enesTufekci Does that mean that even though we don't see the object animate anymore, it still does? (but so slightly that we cannot see it? 🤔).

**Comment by futuun** [comment]
> @enesTufekci Does that mean that even though we don't see the object animate anymore, it still does? (but so slightly that we cannot see it? 🤔).

Yes, and that’s quite common thing with spring based animations.
There are two properties (`restSpeedThreshold` & `restDisplacementThreshold`) that allow you to define when your spring should be considered at rest.
Check [this](https://facebook.github.io/react-native/docs/animated#spring) for description of those two.

**Comment by wcandillon** [comment]
woah thank you so much 🙏🏻

**Comment by wcandillon** [comment]
@JonnyBurger I noticed the exact same "issue" and fixed it outside the spring function. You can find an example at https://github.com/wcandillon/can-it-be-done-in-react-native/blob/master/tinder-swiping/components/Profiles.js

**Comment by hoffmannjan** [comment]
> @JonnyBurger Thank for sharing this solution. I will likely try it.
> 
> I noticed the exact same "issue" and fixed it outside the spring function. You can find an example at https://github.com/wcandillon/can-it-be-done-in-react-native/blob/master/tinder-swiping/components/Profiles.js.
> 
> I'm glad that we can share/improve these use cases together.

Could you share which line fixes this issue?
