### ISSUE TITLE
[Question] On the Interactable.View implementation

### ISSUE THREAD

**Issue by wcandillon** [kmagiera/react-native-reanimated#134]
I was checking the `Interactable.View` implementation in reanimated (great job btw!). I noticed that you don't use `spring` anywhere. I would be interested to know how you manage the snap effect without it?

Thank you for your great work 🙋🏼‍♂️

**Comment by osdnk** [comment]
Hi, take a look here:
https://en.wikipedia.org/wiki/Harmonic_oscillator

@kmagiera has implemented harmonic oscillator's behaviour
```
function springBehavior(dt, target, obj, anchor, tension = 300) {
  const dx = sub(target.x, anchor.x);
  const ax = divide(multiply(-1, tension, dx), obj.mass);
  const dy = sub(target.y, anchor.y);
  const ay = divide(multiply(-1, tension, dy), obj.mass);
  return {
    x: set(obj.vx, add(obj.vx, multiply(dt, ax))),
    y: set(obj.vy, add(obj.vy, multiply(dt, ay))),
  };
}
```

**Comment by wcandillon** [comment]
Thks a lot, really appreciate it.
