### ISSUE TITLE
Not smooth animation

### ISSUE THREAD

**Issue by KakarN** [kmagiera/react-native-reanimated#136]
I have been playing with reanimated with the help of [this tutorial](https://www.youtube.com/channel/UClwd5cLFErEngjSvCYpGY5Q), but I still find it sometimes stutter. It's not that smooth I suppose. You can check out this [snack](https://snack.expo.io/@codedaily/reanimatedopacitydrag) and confirm. Could you tell me what could be wrong so that I can improve? Or is this performance valid?

**Comment by osdnk** [comment]
Hi, @KakarN 
Have you tried only on online simulator? 
I opened you and everything seems to be smooth:
![image](https://user-images.githubusercontent.com/25709300/49340641-1fb50980-f643-11e8-8729-531da0fd473b.png)

**Comment by osdnk** [comment]
Please also check if you use the newest version of library.

**Comment by osdnk** [comment]
Author of the issue appears to be not responsive. I'll reopen it if more data provided.
