### ISSUE TITLE
Would a measure(ref) function make sense?

### ISSUE THREAD

**Issue by wcandillon** [kmagiera/react-native-reanimated#137]
I've implemented a ScrollView with reanimated (and gesture handler) since I wanted bidirectional scrolling (I don't think there is a component in RN that provides that unless I missed it?). Anyways, I'm super happy with the end result. It shows that people how are looking to build consistent experiences across iOS and Android can use gesture handler and reanimated to declare complex high-level components.

However, in my case, I'm lucky because I know statically the upper bound of my x and y scrolling. If the content size would change dynamically, would it make sense to have a `measure(ref)` function so we can set the scroll upper bound? What are your thoughts on this?

It's not something that I need but I was just wondering how I would deal with it if this came up. 

Thanks for the great work ❤

**Comment by wcandillon** [comment]
I just realized that there is a wrapped version of <ScrollView> with gesture-handler so this might not necessary at.

**Comment by wcandillon** [comment]
I actually now thinking about other use cases where this would be useful, like shared transitions 🤔

**Comment by mmazzarolo** [comment]
> I just realized that there is a wrapped version of with gesture-handler so this might not necessary at.

Hey @wcandillon ! I'm working on the same "feature" :) 
Basically a zoomable ScrollView.  
Any tip on how you solved it? 
I was able to make it work correctly starting from the imageviewer example, my only issue right now is that the content of the scrollview might change size at runtime and I'd need to provide the new updated size to the translations.   


> (I don't think there is a component in RN that provides that unless I missed it?)
On iOS you can use the original ScrollView. On Android there's nothing like that.

**Comment by wcandillon** [comment]
@mmazzarolo Wrapping an `<PanGesture>` and a `<ScrollView>` won't work on Android? Why?

**Comment by mmazzarolo** [comment]
@wcandillon I meant that on iOS you get that functionality out of the box by playing with the `maximumZoomScale` and `minimumZoomScale` props. They work both vertically and horizontally.  

On Android you have to implement it yourself.

**Comment by wcandillon** [comment]
@mmazzarolo I stumbled exactly on the same problem than the one you describe and I didn't find an adequate solution yet, have you? :)
