### ISSUE TITLE
Invalid TypeScript types

### ISSUE THREAD

**Issue by henrikra** [kmagiera/react-native-reanimated#138]
Hello I just started using this library and so far so good!

The first problem I faced was that TS types were incorrect.

Basically I just copy pasted this example:
![image](https://user-images.githubusercontent.com/12229968/49296137-1cdddb80-f4c0-11e8-8409-4c933f05ccee.png)

But then I get errors like this: 
![image](https://user-images.githubusercontent.com/12229968/49296157-29623400-f4c0-11e8-9082-4e50f40f4ec1.png)
![image](https://user-images.githubusercontent.com/12229968/49296164-2e26e800-f4c0-11e8-8821-4951306e9706.png)

So the code *works* but there is problem with TS types. Could you guys fix it because I JUST started using this library so I am not sure how the fix TypeScript types correctly because I have no knowledge of the codebase yet :)

**Comment by osdnk** [comment]
Hi @henrikra,
Welp, you're right, there's no typings for backard compatible API
