### ISSUE TITLE
Using "new Value()" on an Android device will prompt the error message "wrong style form"

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [kmagiera/react-native-reanimated#142]

**Comment by osdnk** [comment]
It's required to initialize with some value

**Comment by NrqhEIcsRi004** [comment]
Height:new Value()
When the value is empty, it can run normally on iOS, and the height is high.
Animated.View does not seem to support onLayout

**Comment by NrqhEIcsRi004** [comment]
I hope that Android can get the default high....@osdnk thx
