### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Andarius** [kmagiera/react-native-reanimated#150]
I'm trying to run the **Example** but i get the following error: 

`Unable to resolve module './../react-transform-hmr/lib/indexj.js' `

An idea ?

**Comment by osdnk** [comment]
Hi @Andarius,
Please use `yarn start` instead of `react-native start`. If it won't help, use `--reset-cache` flag also.

**Comment by Andarius** [comment]
Thanks ! Could be worth mentioning it in the README :)
