### ISSUE TITLE
[FEATURE] add more trigonometry operator

### ISSUE THREAD

**Issue by F4b1n0u** [kmagiera/react-native-reanimated#158]
HI guys ! :)

I was wondering if it was planned to add function like 'atan' in a near future ?

I do need it to calculate an angle :)

I actually tried to add it myself by mimicking how cos was added, 
but sadly it crases right away :p, 'm sharing with you how I tried to do it

If someone who be keen enough to give me a hand to add it myself :)

once done, I will not mind rinsing a proper PR to let everybody enjoy it as well :)

FYI:
I'm using expo SDK31, which seems to rely on react-native-reanimated@1.0.0-alpha.10
[here is the branch of my project](https://github.com/F4b1n0u/gesture-touch-release/tree/atan)

[here is what I'm trying to reproduce](https://github.com/F4b1n0u/gesture-touch-release/blob/master/ScreenRecording_12-19-2018%2011-58-52.MP4?raw=true)

you will need to apply this changes on the lib to be in the same state as me

you just have to hold the button and when the expansion is over, the 'atan' kick in and the app crashes, I haven't try android yet too

![add atan](https://user-images.githubusercontent.com/6585690/50523373-bac8c400-0ac7-11e9-888e-a06df90b323e.png)

**Comment by F4b1n0u** [comment]
[here are my changes](https://raw.githubusercontent.com/F4b1n0u/gesture-touch-release/master/add%20atan.png)

**Comment by F4b1n0u** [comment]
actually !, it seems that what I have done was doing the trick :)
the crash was due to 2 mistakes:
division of animated values directly without using the divide operator,
and the classic division by zero :)

so yeah it seems to work now ! \o/

let me know if you wish me to do a PR, tried to push a branch but I had permission issues, so I'm obviously not doing something properly :)

but I would be very proud to bring a little contribution to this project ! xD

**Comment by senthilsivanath** [comment]
@F4b1n0u  Please add atan2 as well

**Comment by F4b1n0u** [comment]
I will raise my PR soon, but unfortunately, my knowledge of the native side is limited so not sure I will be able to add atan2,
the thing is the atan, cos etc, expect only one argument (SingleOperator), but atan2 expect 2, so not sure what are the implications in this case, but I invite you to have a look at my PR to see if you can do it :)
good luck

**Comment by senthilsivanath** [comment]
Have a local branch where I got atan2 working along with atan. Just refer add method code for two parameters. I m ok to raise a PR if required.

Thanks
Senthil

Sent from my iPhone

On 08-Jan-2019, at 6:28 PM, Fabien BEHIER <notifications@github.com<mailto:notifications@github.com>> wrote:


I will raise my PR soon, but unfortunately, my knowledge of the native side is limited so not sure I will be able to add atan2,
the thing is the atan, cos etc, expect only one argument (SingleOperator), but atan2 expect 2, so not sure what are the implications in this case, but I invite you to have a look at my PR to see if you can do it :)
good luck

**Comment by iwikal** [comment]
atan2 isn't strictly necessary, as it can be constructed from `atan` and other existing functions.

**Comment by wcandillon** [comment]
While it looks like we can still build `atan2` with `atan` (https://en.wikipedia.org/wiki/Atan2), it would still be convenient to have `atan2` out of the box.

**Comment by iwikal** [comment]
Sure, I was just saying I'd rather have a PR merged sooner rather than
waiting for atan2.

**Comment by wcandillon** [comment]
@iwikal absolutely!
I ended up writing these two functions in case someone needs them with expo <= 32: https://gist.github.com/wcandillon/7250e806c3f66e8e82484d7dcdc35501
They seem to work well for me.

**Comment by iwikal** [comment]
@wcandillon Nice! I ended up doing something similar until we ditched expo for a variety of reasons, so now I can use the latest version of everything.

On that note, shouldn't this issue be closed now? @kmagiera

**Comment by osdnk** [comment]
should be closed. Thanks!
