### ISSUE TITLE
react-native run-ios fails

### ISSUE THREAD

**Issue by garfieldnate** [kmagiera/react-native-reanimated#161]
I followed the instructions in the readme as well as I could, but I ended up with this error message after `react-native run-ios`:

    ** BUILD FAILED **

    The following build commands failed:

        PhaseScriptExecution Install\ Third\ Party /Users/nglenn/dev/workspaces/web_workspace/react-native-reanimated/Example/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
    (1 failure)

    Installing build/Build/Products/Debug-iphonesimulator/ReanimatedExample.app
    An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
    Failed to install the requested application
    An application bundle was not found at the provided path.
    Provide a valid path to the desired application bundle.
    Print: Entry, ":CFBundleIdentifier", Does Not Exist

    Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ReanimatedExample.app/Info.plist
    Print: Entry, ":CFBundleIdentifier", Does Not Exist

    Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ReanimatedExample.app/Info.plist
    Print: Entry, ":CFBundleIdentifier", Does Not Exist

        at checkExecSyncError (child_process.js:621:11)
        at Object.execFileSync (child_process.js:639:13)
        at Promise.then (/Users/nglenn/dev/workspaces/web_workspace/react-native-reanimated/Example/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
        at process.internalTickCallback (internal/process/next_tick.js:77:7)

I have `yarn start` running in a separate terminal window with the following output:

     yarn start
    yarn run v1.12.3
    $ node node_modules/react-native/local-cli/cli.js start --config ../../../../metro.config.js
    ┌──────────────────────────────────────────────────────────────────────────────┐
    │                                                                              │
    │  Running Metro Bundler on port 8081.                                         │
    │                                                                              │
    │  Keep Metro running while developing on any JS projects. Feel free to        │
    │  close this tab and run your own Metro instance if you prefer.               │
    │                                                                              │
    │  https://github.com/facebook/react-native                                    │
    │                                                                              │
    └──────────────────────────────────────────────────────────────────────────────┘

    Looking for JS files in
       /myworkspace/react-native-reanimated/Example
       /myworkspace/react-native-reanimated

    Loading dependency graph, done.

**Comment by osdnk** [comment]
Hi, @garfieldnate 
I've tried to run example from master and observe no problem. If you still face the problem, consider using XCode for first build

**Comment by litinskii** [comment]
Same problem PhaseScriptExecution
