### ISSUE TITLE
[BUG] call node does like string value on android

### ISSUE THREAD

**Issue by F4b1n0u** [kmagiera/react-native-reanimated#165]
I update an SVG path by calling something like
```
this. _wholeInPath = concat(
   ///strings
)

...

call([ this._wholeInPath ], ([ wholeIntPath, ]) => {
    this._loopInElement && this._loopInElement.setNativeProps({ d: wholeIntPath })
}),
```

it does the job on iOS, but on android I end up with a cast issue

![screenshot_20190109-142722](https://user-images.githubusercontent.com/6585690/50905476-d4003780-141a-11e9-9991-568adbb81d04.png)

after looking at the JSCallNode.java, the evaluate function return indeed a Double,

not sure what type can be used here to sort my issue without breaking the case when we need a Double.

does someone has an idea, what I should do ?

**Comment by F4b1n0u** [comment]
I could delegate the concat to the JS thread by passing all the variables (which are numbers) I need to generate my path to the call function, but it feels like the data should be as processed as possible on the Native side, which is I think the reason of this lib in the first place no ? :)

**Comment by F4b1n0u** [comment]
actually I managed to fix it by replacing

```
args.pushDouble(node.doubleValue());
```

to this

```
if (node.value() instanceof String) {
  args.pushString((String) node.value());
} else {
  args.pushDouble(node.doubleValue());
}
```

in the `JSCallNode.java` file

**Comment by osdnk** [comment]
Hi @F4b1n0u,
Do you want to make a PR with this change? I'll merge it immediately :)

**Comment by wcandillon** [comment]
I'm also hitting this bug, is this merged already? If not let me know if I can help. I've made a small snack to reproduce it: https://snack.expo.io/@wcandillon/aW5zYW

**Comment by osdnk** [comment]
https://github.com/kmagiera/react-native-reanimated/pull/198

I fixed it but I need approve from one of maintainers.
@adamczyk777 @kmagiera @notbrent

**Comment by osdnk** [comment]
Fixed on master

**Comment by RatebSeirawan** [comment]
I am on 1.7 and it's crashing on android, IOS is fine tho

any suggestions?

**Comment by Hani-Ghazi** [comment]
> I am on 1.7 and it's crashing on android, IOS is fine tho
> 
> any suggestions?

I also have the same issue here using @react-navigation/material-top-tabs 5.1.1
