### ISSUE TITLE
timing(..).start() seems broken

### ISSUE THREAD

**Issue by ericvicenti** [kmagiera/react-native-reanimated#167]
Hey team, I have a pretty simple example of Animated.timing.start that doesn't work. In my application, it fails silently, but these repros also demonstrate:

### Repro Snippet

```js
export default class App extends React.Component {
  state = { progress: new Animated.Value(0.15) };
  componentDidMount() {
    // this should cause the message to fade in, but it does not
    Animated.timing(this.state.progress, {
      toValue: 1,
      duration: 500,
      easing: Easing.out(Easing.cubic)
    }).start(() => {
      // this should get called after ~500ms, but it does not
      console.log("Transition complete");
    });
  }
  render() {
    return (
      <Animated.View
        style={[{ opacity: this.state.progress }, styles.container]}
      >
        <Text style={styles.paragraph}>Hello Reanimated</Text>
      </Animated.View>
    );
  }
}
```

### Snack (crashes expo)

https://snack.expo.io/rkIOPnLzV

### Native Repo (crash tested on iOS)

https://github.com/ericvicenti/reanimated-bug

<img width="1680" alt="screen shot 2019-01-11 at 4 35 13 pm" src="https://user-images.githubusercontent.com/1483597/51066748-fc299b00-15c0-11e9-963e-d004a8330a31.png">

**Comment by F4b1n0u** [comment]
I think you cannot use the same API as the React.Animated to deal with animation,

in Reanimated the animation are manage via a clock, I advise you to have a look at the readme of this repo and to look at the implementation of the example, they are pretty useful :)

have a good one

**Comment by ericvicenti** [comment]
I've used the clock before, but it is very inconvenient compared to the animated `start` API.

It used to work with Reanimated, and I think that compatibility is a goal for this library, otherwise people won't be able to adopt it.

**Comment by kantorm** [comment]
@ericvicenti Try to use `Easing` from `react-native-reanimated`

**Comment by ericvicenti** [comment]
@kantorm, that does fix the issue in the standalone repo, thanks!

But.. there is still an exception firing on the Expo snack: https://snack.expo.io/S1m444cGN

I will check against my internal project, but I think there is another way to reproduce the timing start bug. I'll try to get the minimal example app to demonstrate it.

**Comment by ericvicenti** [comment]
I'm going to close this for now because I can't find a simple way to reproduce the issue.. I'll re-file if I pin it down
