### ISSUE TITLE
[BUG] Unable to resolve module `react-native/Libraries/Components/View/ViewStylePropTypes`

### ISSUE THREAD

**Issue by ddwwcruz** [kmagiera/react-native-reanimated#186]
Full error message:
```
error: bundling failed: Error: Unable to resolve module `react-native/Libraries/Components/View/ViewStylePropTypes` from `/home/wyn/Code/react-native/MyProject/node_modules/react-native-reanimated/src/createAnimatedComponent.js`: Module `react-native/Libraries/Components/View/ViewStylePropTypes` does not exist in the Haste module map
```

Package Versions:
* react: 16.6.3
* react-native: 0.58.3
* expo: 32.0.4

**Comment by osdnk** [comment]
Fixed in new release:
https://github.com/kmagiera/react-native-reanimated/commit/4a0798b752b5f603784f35768d93cb77231d9953

**Comment by 911flasher** [comment]
reproduced with
 "expo": "^32.0.0",
    "react": "^16.8.4",
    "react-native": "^0.59.1",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.4.1",
    "react-navigation": "^2.17.0"

**Comment by mauriciord** [comment]
@911flasher did you solve the issue?

**Comment by MayoudP** [comment]
> @911flasher did you solve the issue?

This one can potentially fix it for you, have a look : https://github.com/shoutem/ui/issues/424#issuecomment-471464344
