### ISSUE TITLE
Android only -> E/ReactNativeJS: undefined is not an object (evaluating '_ReanimatedModule.default.configureProps')

### ISSUE THREAD

**Issue by jatin-mohindra** [kmagiera/react-native-reanimated#207]
Getting this error in logcat only on android:
<img width="1326" alt="screenshot 2019-03-08 at 17 39 36 10" src="https://user-images.githubusercontent.com/47021089/54027953-54e47100-41c9-11e9-87ca-e639c76d6854.png">

**Comment by jatin-mohindra** [comment]
@osdnk can you help me with this

**Comment by melkayam92** [comment]
Hey @jatin-mohindra ,

Try to open the app from Android Studio and build it from there - you need to build the APK again so the native modules will be available to you.

**Comment by jatin-mohindra** [comment]
> Hey @jatin-mohindra ,
> 
> Try to open the app from Android Studio and build it from there - you need to build the APK again so the native modules will be available to you.

@melkayam92 i tried that as well but it didn't work

**Comment by dsznajder** [comment]
@jatin-mohindra Could you provide more info about your setup? Maybe you forgot to link RNGH module. Try link it manually, it helps sometimes.

**Comment by jatin-mohindra** [comment]
> @jatin-mohindra Could you provide more info about your setup? Maybe you forgot to link Reanimated module. Try to link it manually, it helps sometimes.

@dsznajder I tried that as well using the react-native link command. I am using Reanimated module as a peer dependecy for **react-native-tab-view** alongwith react-native-gesture-handler.

**Comment by iktw** [comment]
Make sure that you've added
`new ReanimatedPackage(),`in MainApplication.java under `getPackages`

Import from: `import com.swmansion.reanimated.ReanimatedPackage;`

**Comment by tabfed** [comment]
me too

**Comment by rzdchen** [comment]
me too,did you fix it?

**Comment by rzdchen** [comment]
@iktw  it work,thank you

**Comment by jatin-mohindra** [comment]
closing the issue; the solution provided by @iktw works.

**Comment by AHStudyBank** [comment]
@iktw , fix isnt working for me, anything changed?

**Comment by IronTony** [comment]
for me too, not working

**Comment by douglassoldan** [comment]
He's referring to this step, for react-native 0.59 or lower:
react-native link react-native-reanimated
react-native link react-native-gesture-handler

**Comment by gazedash** [comment]
@kmagiera I have this problem as well, I did react-native link, cleaned gradle cache, built an app and it shows this error

**Comment by hangindan** [comment]
Same problem using react-native@0.60.4. The only way to get Android to work was to link it. iOS left using dynamic link.

**Comment by sobanarshad85** [comment]
just uninstall the app and reinstall with react-native run-android

**Comment by renaultscabora** [comment]
> just uninstall the app and reinstall with react-native run-android

after a long day, it work to me. thx

**Comment by sobanarshad85** [comment]
> > just uninstall the app and reinstall with react-native run-android
> 
> it work. thx

Thanks for acknowledgment

**Comment by lorenjohnson** [comment]
@sobanarshad85 yes, that was the missing piece for me as well. Thank you!

* To others, do not manually link this if >= 0.6 react-native, just delete the installed dev Android app in the emulator and re-run, and that's when the auto-linking will happen.
