### ISSUE TITLE
outputRange cannot include color string #00AAAA

### ISSUE THREAD

**Issue by b3hz4d** [kmagiera/react-native-reanimated#208]
I can't use string for output range for using in colors

**Comment by heyman333** [comment]
same👍

**Comment by heyman333** [comment]
AH, I got it. U have to use it like this `Animated.color(242, 81, 48)`

**Comment by niloufarMakhzani** [comment]
I'm facing the same problem for setting degree for rotate value in react-native-reanimated. It says invariant violation: outputRange cannot include 0deg, How can I use 180degree as a number?

**Comment by bdrobinson** [comment]
Judging by some of [the examples](https://github.com/kmagiera/react-native-reanimated/blob/master/Example/rotations/index.js), you can use the `concat` operator:
```js
const {concat} = Animated
const degrees = new Animated.Value(90)
const degreesWithSuffix = concat(degrees, "deg")
```
