### ISSUE TITLE
[Question] On snappable example, how to implement start / stop button

### ISSUE THREAD

**Issue by artechventure** [kmagiera/react-native-reanimated#229]
Hi, our product just implemented reanimated, which uses similiar code with Example/Snappable.

On that exmaple, this.transX is a condition node which is triggered by gesture events, and a clock.
But I am wondering, how to combine above with a start / stop button.
I am trying to do it with spring().start() / spring().stop(), but it is hard to combine with gesture events. Any solutions will help us a lot.
Thank You!

**Comment by beautyfree** [comment]
@artechventure
