### ISSUE TITLE
Typescript concat typing

### ISSUE THREAD

**Issue by RWOverdijk** [kmagiera/react-native-reanimated#233]
I'm doing this:

```ts
return concat(transformation, 'deg');
```

And I'm getting this:

> TS2345: Argument of type '"deg"' is not assignable to parameter of type 'AnimatedNode<string>'.

Am I doing something wrong or are the typings a bit off here?

**Comment by wcandillon** [comment]
This issue has been solved in the latest version of the type declaration. I would suggest closing this issue.

**Comment by RWOverdijk** [comment]
Oh, okay. Thanks for the update.
