### ISSUE TITLE
I'cant get build on iOS Illegal type 'CATransform3D' 

### ISSUE THREAD

**Issue by berkaybeyaz1** [kmagiera/react-native-reanimated#236]
I'cant get build on iOS, xcode said` Illegal type 'CATransform3D' (aka 'struct CATransform3D') used in a boxed expression`.

**Error and File Location**: node_modules/react-native-reanimated/ios/Transitioning/REAAllTransitions.m:227:29: Illegal type 'CATransform3D' (aka 'struct CATransform3D') used in a boxed expression

![Screen Shot 2019-04-09 at 8 39 36 PM](https://user-images.githubusercontent.com/7584428/55822222-ccc6f380-5b07-11e9-8e29-f181708e634e.png)

![Screen Shot 2019-04-09 at 8 39 42 PM](https://user-images.githubusercontent.com/7584428/55822223-ccc6f380-5b07-11e9-90ac-f1a8b3a1b54b.png)

**Comment by brunnohofmann** [comment]
Im facing the same problem to.

**Comment by zeekay18** [comment]
I'm also facing this issue. Has anyone seen a solution

**Comment by engineerahkhani** [comment]
me either🤦‍♂️

**Comment by krszwsk** [comment]
Also facing this issue. React Native `0.57.8`.

**Comment by krszwsk** [comment]
I created a PR for this issue: https://github.com/kmagiera/react-native-reanimated/pull/254

**Comment by bit-sun** [comment]
This issue happens in Xcode 9.3, but in Xcode 10.1 the code can be built successfully.

**Comment by osdnk** [comment]
Why can't you use the new Xcode version?

**Comment by bit-sun** [comment]
@osdnk  I am using the new Xcode. I only intended to tell others to upgrade Xcode to solve this issue.

**Comment by osdnk** [comment]
I didn't want to sound bad 😓. I mean that I want to figure out if there's any reason we need to consider for provide backward compatible API for old XCode.
