### ISSUE TITLE
Cannot read property 'Together' of undefined

### ISSUE THREAD

**Issue by moisesynfam** [kmagiera/react-native-reanimated#238]
Hello, I'm trying to use the Transition component but it's returned undefined when imported from the module.

**Comment by adamczyk777** [comment]
Hey there, Are you sure you are using the latest version of reanimated? It is a relatively new feature which was introduced in the latest version of the library.

**Comment by adamczyk777** [comment]
Closing this issue as there is no interaction. I will reopen if there will be any news about it.

**Comment by moisesynfam** [comment]
Sorry for disappearing. I have installed the latest version (1.0.1) and no longer have this issue.
