### ISSUE TITLE
Start animation from JS (on button click)

### ISSUE THREAD

**Issue by mralj** [kmagiera/react-native-reanimated#245]
Hello,

I creating BottomDrawer similar to [this one](https://github.com/jacklein/rn-bottom-drawer). But I am stuck on opening / closing modal from another component. 

I have looked at code from [Swipeable](https://github.com/kmagiera/react-native-gesture-handler/blob/master/Swipeable.js#L269) and it looks pretty straightforward, but I am unable to make it work for me.

I am setting `ref` to my `BottomDrawer`  component on my `Screen`
From `Screen` I am calling `bottomDrawer.open()` which gets executed on JS thread (I can see it calling `console.log`), but  `BottomDrawer` doesn't open. 

Here is code for `open` method:

```
public open() {
    tron.log("OPEN RECEIVED");
    const clock = new Animated.Clock();
    this.runSpringAnimation(clock, new Animated.Value(20), new Animated.Value(0));
  }
```

`runSpringAnimation` is pretty much same as in [Snappable example](https://github.com/kmagiera/react-native-reanimated/blob/master/Example/snappable/index.js#L30), and it works in combo with [RN Gesture Handler](https://kmagiera.github.io/react-native-gesture-handler/) (what I am doing is simillar to Snappable example, when Gesture ENDs, calculate `snapPoint` and run `springAnimation` to that point)

Can someone please explain to me what am I doing wrong 😊?

**Comment by dsznajder** [comment]
@mralj I do not have a full context of your code but I have managed to create `onPress` animations with this code:
https://snack.expo.io/ByL5dk0FN

If something is not clear or does not cover your case, please share some more code :).

**Comment by mralj** [comment]
Thank you very much for your response, I have had made stupid mistake:

`this.runSpringAnimation(clock, new Animated.Value(20), new Animated.Value(0))`

Returns value and based on that value `translateY` was calculated.

After setting that value like in your example (via just `setValue`) it works as expected :)

**Comment by dsznajder** [comment]
@mralj No problem at all :) If you run into some corner just open next issue and ping me :)
