### ISSUE TITLE
Way to access animated value in JS?

### ISSUE THREAD

**Issue by scottmas** [kmagiera/react-native-reanimated#251]
Hi, I have looked and looked but can't seem to find a way to access an animated value in JS. I'm definitely a novice to this all. All the examples in the Example folder are concerned solely with visual appearance. There are many use cases though where the JS thread actually needs to know the current value of the Animated value. For example, I'm trying to create a drag and drop interface with multiple options and I need to know precisely _where_ the animated value has come to rest (on drag end) so that I can calculate which drag option the user has selected. 

Sorry if this is simply something I missed!

**Comment by wcandillon** [comment]
You can use `call` for that effect. Or on `onChange` might what you are looking for depending on your use case.
For instance:

```
        <Animated.Code>
        {
          () => call([val], ([val]) => alert(val))
        }
        </Animated.Code>
```

I hope this helps.

**Comment by scottmas** [comment]
That's it! Sorry, I simply missed it. There it was all along in the Code example (https://github.com/kmagiera/react-native-reanimated/blob/master/Example/code/index.js)

Thank you!

**Comment by sinodko** [comment]
hello @wcandillon is there any way to get values (to run call's callback) when lifecycle methods are triggered? for example componentDidUpdate or react-navigation's onFocus or any other. I would like to set StatusBar's barStyle according to scrollY value when the screen is focused.  Btw great videos man!

**Comment by computerjazz** [comment]
@sinodko In cases like yours, I use `Animated.Value`s as flags to trigger native events. Something like:

```javascript
onUpdateFlag = new Value(0)
animVal = new Value(0)

componentDidUpdate() {
   this.onUpdateFlag.setValue(1)
}

doThisOnUpdate = ([val]) => {
  console.log(`component updated, my animated value is: ${val}`)
}

render() {
  return (
   <Animated.Code>
        {
          () => onChange(this.onUpdateFlag, [
             cond(this.onUpdateFlag, call([this.animVal]), this.doThisOnUpdate))
             set(this.onUpdateFlag, 0) 
         ])
        }
 </Animated.Code>
  )
}



```

**Comment by nathvarun** [comment]
> You can use `call` for that effect. Or on `onChange` might what you are looking for depending on your use case.
> For instance:
> 
> ```
>         <Animated.Code>
>         {
>           () => call([val], ([val]) => alert(val))
>         }
>         </Animated.Code>
> ```
> 
> I hope this helps.

So an example would be : 
 <Animated.Code>
        {
          () => call([this.scrollY], ([val]) => console.log(val))
        }
        </Animated.Code>

**Comment by sebinq** [comment]
Is it alright to define first argument of onChange as list of two nodes?

**Comment by bharatgupta99** [comment]
Hi, is there a way to get js value inside a callback method. For example, a callback method passed to Animated.ScrollView's onMonentumScrollEnd method?
