### ISSUE TITLE
How to import Reanimated type?

### ISSUE THREAD

**Issue by wcandillon** [kmagiera/react-native-reanimated#261]
I would like to be able to import the reanimated TS which are exported from the Animated namespace. For instance:

```js
const toRad = (deg: Adaptable<number>) => multiply(deg, Math.PI / 180);
```

How can I import the type `Adaptable`? This is how my `tsconfig.json` file look like: https://gist.github.com/wcandillon/aec090043a2b4e75d33fd439d2ec0160

Right now, I'm resorting to write declarations like this:
```
type TimingConfig = Parameters<typeof timing>[1];
type Clock = Parameters<typeof clockRunning>[0];
type Node = ReturnType<typeof add>;
type Adaptable<T> = Node | T;
```

Is there a better way? Or should we change the type declaration? I would like to provide an update but I'm confused on the semantics of the `namespace` keyword in the type declaration

**Comment by satya164** [comment]
Doesn't `Animated.Adaptable` work?

**Comment by wcandillon** [comment]
Yes that works thank you :)
