### ISSUE TITLE
Unable to locate attached view in the native tree

### ISSUE THREAD

**Issue by JulianKingman** [kmagiera/react-native-reanimated#27]
There appears to be related to this line of code, which calls detach sometimes on null nodeId's: https://github.com/kmagiera/react-native-reanimated/blob/f607cebcd4b5f84a0c2b0446288de164dba512a4/src/createAnimatedComponent.js#L153

An easy solution would be to also check for a nodeId, like this:
```javascript
oldPropsAnimated && oldPropsAnimated.__nodeId && oldPropsAnimated.__detach();
```

**Comment by JulianKingman** [comment]
Actually, I'm having issues with this line as well, I suggest the same check
https://github.com/kmagiera/react-native-reanimated/blob/f607cebcd4b5f84a0c2b0446288de164dba512a4/src/createAnimatedComponent.js#L31

**Comment by osdnk** [comment]
Would you mind giving us context of this issue? How to repro it?

**Comment by osdnk** [comment]
Maybe it's fixed. If not, please let me know, @JulianKingman @vincentriemer @trungtin
