### ISSUE TITLE
Content appears to be frozen inside Animated component

### ISSUE THREAD

**Issue by JulianKingman** [kmagiera/react-native-reanimated#28]
For some reason, updates to state and props don't seem to reach the contents of Animated.ScrollView. I can't reliably reproduce it, but it appears to be related to this issue: https://github.com/kmagiera/react-native-reanimated/issues/27
As the issue only occurs together with that one.

Ideas?

**Comment by JulianKingman** [comment]
To add to this, I noticed that content inside `Animated.View` used old state. That is, the state had updated, and logs showed that this was all looking good, but the actual state rendered was the one previous. I hope that makes sense...

**Comment by sanealytics** [comment]
Having the same issue with the example, ImagePreview. I changed state but it does not re-render.

Do we have to send an event?

**Comment by osdnk** [comment]
https://github.com/kmagiera/react-native-reanimated/pull/22
This commits makes this error. I'm trying to figure out what's the problem

**Comment by kitten** [comment]
For anyone who stumbles on this being on `1.0.0-alpha.3`; This behaviour can also be caused (I believe; tbh I didn't dig too deep) by `forceUpdate` being called higher up in your component tree, which react-navigation-fluid-transitions does for instance.
