### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by jeveloper** [kmagiera/react-native-reanimated#288]
Just wanted to start this conversation.
It appears that jetifying (automatically rewriting binary) fails badly.

Anyone had luck with enabling the androidX flag?

**Comment by sunnylqm** [comment]
Can not build on rn 0.60 because of this

**Comment by simonbuerger** [comment]
Jetifying works for me now BTW

**Comment by jeveloper** [comment]
@simonbuerger  are you using the flag only ?

**Comment by simonbuerger** [comment]
@jeveloper no, `npx jetify` postinstall hook

**Comment by kmagiera** [comment]
It's just been merged in #395. Thank you all for reporting
