### ISSUE TITLE
Could not find transition.jar (com.android.support:transition:28.0.0).

### ISSUE THREAD

**Issue by aliazizi** [kmagiera/react-native-reanimated#290]
I'm using libversion 28.0.0 and i get this error

> Could not find transition.jar (com.android.support:transition:28.0.0).
  Searched in the following locations:
      https://dl.google.com/dl/android/maven2/com/android/support/transition/28.0.0/transition-28.0.0.jar

I figure out there is no transition-28.0.0.jar and only transition-28.0.0.aar exist so I go to build.gradle and change it to this

`implementation "com.android.support:transition:${rootProject.ext.supportLibVersion}@aar"`

Now everythink looks fine.

Is it a better way to do that?

**Comment by Ashkan-Oliaie** [comment]
> react-native link react-native-reaninmated

after linking I seem not to be able to get https://dl.google.com/dl/android/maven2/com/android/support/transition/28.0.0/transition-28.0.0.jar

**Comment by ludu12** [comment]
Not sure I ran into the same issue or not but if you are using a newer version of RN  (0.60+ I believe) then you may need to use the Jetifier to update this library as RN has movied to using AndroidX https://github.com/facebook/react-native/issues/23112

See this comment here: https://github.com/facebook/react-native/issues/25483#issuecomment-508446776

**Comment by aliazizi** [comment]
I use react native 59

**Comment by kmagiera** [comment]
Closing this since #395 migrates the library to use androidx and hence the problem with transition package should no longer occur

**Comment by mifi** [comment]
Having the same problem on 0.59 when using `jetify -r` as suggested.

**Comment by aliazizi** [comment]
@mifi change build.gradle of this project to `implementation "com.android.support:transition:${rootProject.ext.supportLibVersion}@aar"`

**Comment by mifi** [comment]
Thanks, but I upgraded to 0.61 eventually and now everything works
