### ISSUE TITLE
Issue with `concat` typescript typing   

### ISSUE THREAD

**Issue by yjose** [kmagiera/react-native-reanimated#296]
Hi, first of all, thanks for the great work.
I`m trying to use the `concat` function to handle a rotation animation like the following:  
```js
const rotateZ =  concat(rotate, 'deg');
```
And I'm getting this error :
```
const rotate: Animated.Node<number>
Argument of type 'AnimatedNode<number>' is not assignable to parameter of type 'AnimatedNode<string>'.
  Type 'number' is not assignable to type 'string'.
```
which I think is not normal.
I tried to check the ts typing from GitHub repo: https://github.com/kmagiera/react-native-reanimated/blob/5f00eb4e7197379ad43eed13232b174ff08d52a4/react-native-reanimated.d.ts#L222.

but inside my node_modules file, I Have the following typing 
```js
  export function concat(
      a: AnimatedNode<string>,
      b: AnimatedNode<string>,
      ...others: AnimatedNode<string>[]
    ): AnimatedNode<string>;
```
I am running the last version:  1.0.1

**Comment by wcandillon** [comment]
This fix is not shipped in 1.0.1 unfortunately. It should be available in the next release. I would suggest closing this issue.

**Comment by yjose** [comment]
hi @wcandillon, when the new version with fix is estimated to be released, I am having some bad time when  I want t build my own lib 😆

**Comment by wcandillon** [comment]
@yjose In the meantime you can use a functions such as this one: https://github.com/wcandillon/react-native-redash/blob/master/src/SVG.ts#L147. It will bypass the type error and you can write things such as `animatedString'${hello} ${world}'`

**Comment by rnnyrk** [comment]
@wcandillon I'm facing the same issue with the exact same code from your course. Any idea why this is happening? Running `react-native: 0.61.3`, `react-native-reanimated 1.4.0`
<img width="1249" alt="Screenshot 2019-11-16 at 12 10 22" src="https://user-images.githubusercontent.com/4519142/68992328-26e02200-086a-11ea-9cda-55d8bc419192.png">

**Comment by samiede** [comment]
I have that same problem working on the drag to sort example. I can not get past this step as 'useCode() first argument should be a function that returns an animation node.' is thrown.

**Comment by rnnyrk** [comment]
@samiede see https://github.com/notifications/beta/MDE4Ok5vdGlmaWNhdGlvblRocmVhZDYzNDAwMDc4NTo0NTE5MTQy?query=

**Comment by samiede** [comment]
I see. I tried using the callback like this:
`useCode(() => block())` but it still did not work for me. Im ok with using Animated.Code for now :)
