### ISSUE TITLE
Issue with AnimateStyle<> typing

### ISSUE THREAD

**Issue by wcandillon** [kmagiera/react-native-reanimated#297]
While the typing supports perfectly top-level properties and style properties (kudos to that because the RN Animated API types them as any), there seems to be an issue with transform properties which are one level of nesting deeper.

For instance:

```tsx
const scale = new Value(1);
const opacity = new Value(1);
<Animated.View style={{ opacity }} /> // Work great
<Animated.View style={{ transform: [{ scale }] }} /> //  type error
```

I looked at the type definition `AnimateStyle` in `react-native-reanimated.d.ts` but this type definition is challenging for me to understand. I would love to help to solve this issue if pointed to the right direction though.

**Comment by adamczyk777** [comment]
Hey @wcandillon, we can take a look into this as I have the same issue RN

**Comment by wcandillon** [comment]
Sorry about that. This has been fixed.

**Comment by prithweedas** [comment]
I'm having the same issue, can anyone help?
I'm using
"react-native": "0.59.10"
"react-native-reanimated": "^1.3.0"

**Comment by wcandillon** [comment]
@prithweedas can you provide a small code snippet?

**Comment by prithweedas** [comment]
```javascript
const Example = () => {
  const { translationX, gestureHandler } = horizontalPanGestureHandler()
  return (
    <View style={styles.container}>
      <PanGestureHandler {...gestureHandler}>
        <Animated.View style={{ transform: [{ translateY: translationX }] }} />
      </PanGestureHandler>
    </View>
  )
}
```
And here's the type error I'm getting
![error](https://user-images.githubusercontent.com/24864756/65827099-60ee6800-e2ac-11e9-92f9-e83455f6676c.PNG)

**Comment by hastom** [comment]
Same issue 
```
const Test = () => {
  <Animated.View style={{ transform: [ { translateX: new Animated.Value(0)} ] }} />
}
```

Gives error `Type 'Animated.Value(0)' is not assignable to type 'number'`
