### ISSUE TITLE
Animated String Values on Android

### ISSUE THREAD

**Issue by wcandillon** [kmagiera/react-native-reanimated#300]
While string values work great on iOS, they throw errors and crash on Android. 
Below are two examples that work great on iOS but crash or throw on Android with v1.1.0.

## Example 1

```ts
import { TextInput } from "react-native";
const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);

export default () => {
  return (
    <AnimatedTextInput
        underlineColorAndroid="transparent"
        editable={false}
        text={concat("hello ", "world")}
    />
  );
};
```

Error: ConcatNode cannot be cast to a number

## Example 2

```ts
import Svg, { Path } from "react-native-svg";
import Animated from "react-native-reanimated";

const AnimatedPath = Animated.createAnimatedComponent(Path);

export default () => {
  return (
    <Svg style={styles.container} viewBox="0 0 212 239">
      <AnimatedPath
        d={concat(
          "M106,1 C156,1 229.606798,153.786405 206,201 C182.393202,248.213595 31.5199889,252.039978 6,201 C-19.5199889,149.960022 56,1 106,1 Z"
        )}
      />
    </Svg>
  );
};
```

Crashes

**Comment by ken0x0a** [comment]
I'm trying to implement ScrollView using reanimated to get over this issue https://github.com/kmagiera/react-native-reanimated/issues/160, and come up to this crash by following code.

```

**Comment by dodicandra** [comment]
hi, I tried to make the component also from createAnimatedComponent, but I don't know all the props in that component ... I use typescript for passing props, but I also don't know the correct way

i made it like this ..
@wcandillon 

`const AnimatedFlatList: React.FC<FlatListProps<DataProps>> = Animated.createAnimatedComponent(FlatList);`
