### ISSUE TITLE
Bad performance inside large FlatList

### ISSUE THREAD

**Issue by sintylapse** [kmagiera/react-native-reanimated#308]
When I use `Animated` from react-native-reanimated for each item of FlatList with more than 50 items, it shows fine performance with animations, but on js side it becomes very slow and blocks any navigation and other js-side processes. When I replace `Animated.View` with simple `View` - no performance issues

I'm using:
"react-native": "0.56.1",
"react-native-reanimated": "^1.0.1",

**Comment by terrysahaidak** [comment]
Duplicate of https://github.com/kmagiera/react-native-reanimated/issues/194

**Comment by sintylapse** [comment]
@terrysahaidak thanks! I needed `Interactable` functionality from react-native-reanimated https://github.com/kmagiera/react-native-reanimated/blob/master/Example/Interactable.js, but I decided to replace it with react-native-interactable, it have no issues with rendering.

Will be watching #194
