### ISSUE TITLE
"Wrong style form" error on Android

### ISSUE THREAD

**Issue by ethanshar** [kmagiera/react-native-reanimated#331]
Hey, 
I'm receiving this error when running my code on Android. 
I can see it originate from here
https://github.com/kmagiera/react-native-reanimated/blob/06b03a84619cae3c4d9c044b89b7f01d4be8713b/android/src/main/java/com/swmansion/reanimated/nodes/StyleNode.java#L37

but I can't make any sense out the error call stack. 

What can lead to this error? 

using v1.0.0 if that matters

Thanks.

**Comment by Kenpa** [comment]
Hello, i'm facing the same issue, how did you fix it?

**Comment by ethanshar** [comment]
I'm not certain, but looking at my change log I see that it might be related to fact I tried to call `processColor` API (imported from `react-native`) on an undefined value. 
and this was passed to the style of an animated component. 

I would suggest checking that or in general check what exactly are you passing as a style to an animated component. 

good luck!

**Comment by bmovement** [comment]
In my case, I was applying an uninitialized animated value to a style property. Imagine:
```
style={{padding: new Value()}}
```
This threw a `Wrong style form` error on Android, but caused no issue on iOS (maybe it ignored the uninitialized style value or used a value of 0 or something). To fix my issue, I initialized all of my animated values. In my case I just put `0` in them, so they wouldn't have _no_ value. Something like:
```
style={{padding: new Value(0)}}
```
