### ISSUE TITLE
Array conditional for cond undocumented

### ISSUE THREAD

**Issue by louispvb** [kmagiera/react-native-reanimated#34]
I see the following in the example for imageViewer:

```
cond([delta, gestureActive],
   ...
)
```

I'm not sure what the behavior for an array conditional for cond is.

**Comment by louispvb** [comment]
It seems that it behaves as a block of code to be executed, which was a confusing style of programming because delta does not sound like a function invocation. The last node in the block is the condition to evaluate

**Comment by osdnk** [comment]
Maybe it's not very obvious an this example calls to be fixed. However it's fully correct:
`[...]` is a synthatic sugar for `block` which does evaluate each nodes and return the last one as a result, which is an argument for `cond`
