### ISSUE TITLE
Should useCode use a callback as first argument?

### ISSUE THREAD

**Issue by wcandillon** [kmagiera/react-native-reanimated#343]
I'm asking because this is the first time I see a hook with the `deps` parameter where the first parameter is not a callback. In fact, the eslint-hook plugin won't lint for exhaustive dependencies when the first argument is not a callback: https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L64

And indeed now it feels a bit strange that node expression is always "evaluated" for each render even though it should only have effects depending on the `deps` parameter. What are your thoughts on this?

**Comment by kmagiera** [comment]
Hm, now that I think of it I'd say it should always be a callback and never just a list of nodes. Would it make sense to make a breaking change here and change the behavior?

**Comment by wcandillon** [comment]
I'd be ok with ok, should the PR return an error if the param if not of type function?
