### ISSUE TITLE
Causes problems with nested pan handlers on android

### ISSUE THREAD

**Issue by louispvb** [kmagiera/react-native-reanimated#36]
If you test [this snack using reanimated](https://snack.expo.io/ryUWlzXfm) on android you will see that when you try to pan the red box (parent), then it will not pan, however the child circle will pan. After tapping the parent box again the parent box will jump to the position of the drag distance of the blue circle even though the parent was not panned. According to react-native-gesture-handler docs they should be acting independently as one handler should steal control from the other. This works correctly on iOS.

To test if it was a problem with react-native-gesture-handler [I made another snack](https://snack.expo.io/ry5mgf7zX) that uses vanilla RN Animated with native driver and that works correctly on both platforms.

**Comment by osdnk** [comment]
Hi @louispvb,
Could you try with the newest version of expo? I'm not certain which commit fixes this issue, but not it appears to behave perfectly fine. If you still face the problem, please let us know as soon as possible. Now I close the issue, but I'm still observing this case
