### ISSUE TITLE
React Native 0.60.5 has deprecated ListView

### ISSUE THREAD

**Issue by kevinjacyna** [kmagiera/react-native-reanimated#367]
ListView has been deprecated in the last react native upgrade.

ListView is used in Example/interactablePlayground/examples/HandleTouches.js

I believe this is causing the below error.

<img width="388" alt="Screen Shot 2019-08-15 at 7 17 32 PM" src="https://user-images.githubusercontent.com/21031848/63136971-9f94c100-bf91-11e9-8cb4-b83498672b9d.png">

**Comment by Ashkan-Oliaie** [comment]
I got this error on 60.4 as well while debugging was on ,but not with reanimated , still unclear to me though

**Comment by kevinjacyna** [comment]
@Ashkan-Oliaie Hmm yeah let me know if you find a solution to it!

**Comment by Ashkan-Oliaie** [comment]
@kevinjacyna  the only thing that fixed it for me was to going to open Dev Setting and unchecking JS Dev Mode then disabling debugging but I don't know the reason I have't experienced it on reanimated
