### ISSUE TITLE
RN 0.6 reanimated library not linked properly

### ISSUE THREAD

**Issue by tangtai** [kmagiera/react-native-reanimated#372]
I am trying out RN 0.6, in react-native release note it says library now installed will be linked automatically, but when i install reanimated library it gives me error 'native module can't not be null' when look at the xcode project, not library was linked. does anyone else encounters same problem? what is the solution.

**Comment by tangtai** [comment]
so i solved this by unlinking all library, for RN 6.0 you should not link libraries, in project folder do
`cd ios && pod install`

**Comment by empiteranga** [comment]
same issue for android
