### ISSUE TITLE
support for androidx

### ISSUE THREAD

**Issue by ashrithks** [kmagiera/react-native-reanimated#374]
transitions is throwing error in react-native 0.60.5
@kmagiera

**Comment by robonaut** [comment]
Same here

**Comment by ashrithks** [comment]
@robonaut  quick fix for this issue,

```
//need to remove once library updates to androidx
preBuild.doFirst {
    ant.replaceregexp(match: 'android.support.annotation.NonNull;', replace: 'androidx.annotation.NonNull;', flags: 'g', byline: true)
            {
                fileset(dir: '../../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/transitions/', includes: '*.java')
            }
    ant.replaceregexp(match: 'android.support.annotation.Nullable;', replace: 'androidx.annotation.Nullable;', flags: 'g', byline: true)
            {
                fileset(dir: '../../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/transitions/', includes: '*.java')
            }
    ant.replaceregexp(match: 'android.support.transition', replace: 'androidx.transition', flags: 'g', byline: true)
            {
                fileset(dir: '../../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/transitions/', includes: '*.java')
            }
}
```
Add this before dependencies in android/app/build.gradle

**Comment by denieler** [comment]
thanks, you saved hours of my life @ashrithks !

I had error in my app (just to let other people know how to fix that)
```
.../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/transitions/TransitionModule.java:3: error: package android.support.transition does not exist
import android.support.transition.TransitionManager;
```

**Comment by nikhilborana** [comment]
@denieler  +1

**Comment by GuoXianglin** [comment]
@denieler +1；this problem is 'package android.support.transition does not exist'. @kmagiera

**Comment by thevikas** [comment]
```
reanimated/transitions/TransitionModule.java:3: error: package androidx.transition does not exist
import androidx.transition.TransitionManager;
                          ^
```
Used `jetify` to patch to androidx. But is there any additional libs to be added to gradle?

**Comment by dulmandakh** [comment]
Created a PR https://github.com/kmagiera/react-native-reanimated/pull/395.

**Workaround**: run **npx jetify** every time you install/update/remove NPM package.

**Comment by denieler** [comment]
> Created a PR #395.
> 
> **Workaround**: run **npx jetify** every time you install/update/remove NPM package.

amazing workaround 👍 ...

**Comment by kmagiera** [comment]
Closing this as of #395

**Comment by mifi** [comment]
Having the same problem on 0.59.

**Comment by MustaphaGhlissi** [comment]
I got a solution 

Upgrade react-native-reanimated to ^1.5.0 without touching any part of your android config

**Comment by marcosjoao37** [comment]
> I got a solution
> 
> Upgrade react-native-reanimated to ^1.5.0 without touching any part of your android config

Works like a charm. Thank you.
