### ISSUE TITLE
Keyframes

### ISSUE THREAD

**Issue by huzaifaaak** [kmagiera/react-native-reanimated#378]
Hey, 

I have to create a wave. Is it possible for me to use keyframes. I want to do something like this:

const wave = {
    0: {
      translateY: 0
    },
    0.5: {
      translateY: -50
    },
    1: {
      translateY: 0
    }
  };

**Comment by Elf2707** [comment]
What about interpolation, something like this:

```
Animated.interpolate(this.translateAnim, {
  inputRange: [0, 0.5, 1],
  outputRange: [0, -50, 0],
});
```

**Comment by huzaifaaak** [comment]
I used Animated.sequence in Animated.loop.
