### ISSUE TITLE
`createAnimatedComponent` does not support stateless functional components; use a class component instead.

### ISSUE THREAD

**Issue by rodolfovilaca** [kmagiera/react-native-reanimated#38]
## Description
I just started a react native project to play around using `react-native init` and did the linking step.
Changed the default buildToolsVersion of my project from 23.0.1 to 25.0.0, which is the minimum sdk version required.
Only added this line of code to the default react-native project generated:

`import Animated from 'react-native-reanimated;`

And I get this strange error:

```
`createAnimatedComponent` does not support stateless functional components; use a class component instead.
```

I guess this could be related to this https://github.com/kmagiera/react-native-reanimated/commit/cc4ab7fbe704d219a01db00dd440c5600caf70b9 ?

## Steps to reproduce:
- react-native init PlaygroundApp
- yarn add react-native-reanimated
- react-native link react-native-reanimated

## Versions:
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-reanimated": "^1.0.0-alpha.4"

**Comment by kmagiera** [comment]
Hey @rodolfovilaca! Thanks for reaching out. This issue has already been reported and fixed around the same time you posted this issue. Please check if alpha.5 works ok for you https://github.com/kmagiera/react-native-reanimated/releases/tag/1.0.0-alpha.5
