### ISSUE TITLE
Animating multiple nodes at once?

### ISSUE THREAD

**Issue by kaueDM** [kmagiera/react-native-reanimated#382]
Currently, when I need to animate multiple nodes I use `block`. It's great, but as my application need more and more nodes to be animated at once, it becomes an enormous chunk of code of almost identical stuff:

```
    set(someProp, runTiming(clock, someProp, {
      toValue: cond(eq(foo, bar), 1, 10),
      duration: 250,
      easing: Easing.ease
    }))
```

That said, what is the better way to manage multiple nodes at once?

**Comment by davidfarinha** [comment]
@kaueDM By any chance did you find a solution for this in the end?
