### ISSUE TITLE
Android Studio cannot resolve JsonSlurper in build.gradle (line 39)

### ISSUE THREAD

**Issue by BenoitClaveau** [kmagiera/react-native-reanimated#394]
I use 

- Gradle 5.6.2 
- com.android.tools.build:gradle:3.5.0
- Android SDK Tools 26.1.1

**Comment by BenoitClaveau** [comment]
Fixed. I've added supportLibVersion = "28.0.0" in build.gradle.

**Comment by dulmandakh** [comment]
Please close the issue.

**Comment by manosKas** [comment]
can you elaborate ?

**Comment by mixmaker** [comment]
Same issue here, both with `react-native-reanimated` & `react-native-gesture-handler` [here](https://i.stack.imgur.com/32YPe.png) are the logs. And my app gets stuck on splash screen.
 Could you please elaborate how did u fix this?
