### ISSUE TITLE
Deprecated lifecycles componentWillMount

### ISSUE THREAD

**Issue by douglaszaltron** [kmagiera/react-native-reanimated#404]
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AnimatedComponent

**Comment by SaeedZhiany** [comment]
it seems duplicate of #353

**Comment by SaeedZhiany** [comment]
it seems duplicate of #353 and has been resolved by PR #342

**Comment by igoratf** [comment]
@SaeedZhiany I'm still getting the same error and updated the library. Do you know what I can do to fix it?

**Comment by sincraianul** [comment]
The fix hasn't been released in npm yet.

**Comment by IntelliJAbhishek** [comment]
Changes has been merged in 1.3.0. You can close this issue
