### ISSUE TITLE
RN0.61 changes reanimated behavior?

### ISSUE THREAD

**Issue by ShaMan123** [kmagiera/react-native-reanimated#415]
Hi,
I just upgraded to RN 0.61.2.
It seems that nodes are being evaluated infinitely.
Is this possible?
I was using `useCode` hook to trigger changes to nodes but now the chages get triggered again and again.
I'm trying to workaround with `onChange` to make `useCode` stop running.
Is this a known issue? I stumbled upon a PR a week ago discussing something of the sort but can't remember which one.

**Comment by sebinq** [comment]
I have similar problems with 1.3.0 reanimated. My node values are updated even when another node value (in different component) is changed (and no state change is made). Whats worse, even when I push a new screen and then go back, origins screen nodes values are changed. But all these problems dissapears when I remove diffClamp method.

It happens only on 1.3.0. When I downgraded back to 1.2.0 the issue dissapears.

I will try to add demo asap.

**Comment by ShaMan123** [comment]
Thanks for the info!

**Comment by johnhaup** [comment]
Ran into this as well.

RN 0.61.1
Reanimated 1.3.0
Gesture Handler 1.4.1

Wrapping my code in onChange fixed it for me, in case anyone wants to get it working without downgrading.

**Comment by ShaMan123** [comment]
looks like @sebinq found the problem #417 
closing
