### ISSUE TITLE
Pass Interactable animatedValueY value as props to other screen to listen for changes

### ISSUE THREAD

**Issue by pribeh** [kmagiera/react-native-reanimated#423]
I'm looking to pass the animatedValueY of an Interactable to another screen so I can animate a view whenever the Interactable is dragged.

I've imported the interactable into, and added it to the render of, an overlay component which displays overtop of a screen. The animatedValueY is defined as _deltaY (animatedValueY={this._deltaY}). I'm able to easily interpolate _deltaY inside the overlay component. However, I'm struggling to figure out how to pass _deltaY to the underlying screen to animate (via interpolate) the view within the latter.

Is this possible? If so, how?

**Comment by pribeh** [comment]
Never mind – figured it out!

**Comment by lkoehl** [comment]
Can you explain how you did it? Facing the same problem right now

**Comment by pribeh** [comment]
@lkoehl create a separate store (DashboardStore.js) and add the deltaY value to it:

```
class DashboardStore {
 @observable _deltaY = new Animated.Value(this.BOTTOM_SNAP);
}
```

We're using mobx so we add it to the component we want to animate like so:

```
@inject( "DashboardStore")
class NotificationScreen extends React.Component { ... }
```

Then add your interpolate animation like so:

```
// Manipulate the height of another view to match that of the dashboard
this._viewHeight = interpolate(this.props.DashboardStore._deltaY, {
	inputRange: [this.props.DashboardStore.TOP_SNAP, this.props.DashboardStore.BOTTOM_SNAP],
	outputRange: [this.props.DashboardStore.TOP_SNAP, this.props.DashboardStore.BOTTOM_SNAP],
});
```
