### ISSUE TITLE
Examples not working on master - NaN is not usable as a native method argument

### ISSUE THREAD

**Issue by darioceccoli** [kmagiera/react-native-reanimated#424]
I tried to run the examples in the Example folder both using iOS simulator and Android emulator and I get the following error on master.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/29402505/66746025-91233280-ee78-11e9-8da1-4590976675ae.png">

The examples work correctly using latest release (1.3.0).

**Comment by rclai** [comment]
What do we need to do to get this working?

**Comment by darioceccoli** [comment]
`git checkout 1.3.0` to get the working version (if this is what you're asking 🙂)

**Comment by bunyaminmrcn** [comment]
Not working expo or react-native . I will try @darioceccoli `s response

**Comment by osdnk** [comment]
Fixed

**Comment by dellwatson** [comment]
Got this error again, in expo sdk 36.

is it because the expo ? but sdk 36 using v1.4

I'll be back to give more details
