### ISSUE TITLE
[Enhancement] Drag & Drop

### ISSUE THREAD

**Issue by ShaMan123** [kmagiera/react-native-reanimated#431]
Hi guys,
I'm grateful for both libraries, `reanimated` and `gesture-handler`.
I've been working on a light-weight implementation of Drag & Drop for a project of mine that uses both and is quite abstract and flexible.
Are you interested in Drag & Drop as part of this library or `gesture-handler` (or as an opt-in `import react-native-reanimated/DragDrop`)?
I think that the absence of a proper drag and drop library is a major pain.
And in my opinion it should reside under one of your libraries. It makes sense to put it under `gesture-handler` because drag and drop is all about gesture handling but the usage is mostly of `reanimated`.
If so I'd be willing to PR.
If not all is good (I can think of a few design considerations against it).
Regardless, I'll publish it independently.
Long live open source.
And thanks again for these excellent libraries.

**Comment by ShaMan123** [comment]
WIP [rn-drag-drop](https://github.com/ShaMan123/rn-drag-drop)

**Comment by osdnk** [comment]
Maybe try do add this to react-native-redash?

**Comment by ShaMan123** [comment]
thanks man.
