### ISSUE TITLE
Can I animate the opacity of a shadow?

### ISSUE THREAD

**Issue by erickreutz** [kmagiera/react-native-reanimated#44]
In the readme it states one of the goals as being

> No more “useNativeDriver” – all animations run on the UI thread by default

Could I animate the opacity of a shadow or the related shadow properties? What style props are native animations limited with this lib?

**Comment by osdnk** [comment]
Hi @erickreutz,
I'm certain that this case calls for being described better in README. 
But for now let me explain it briefly here:
RN Reanimated is kind of fork of RN's Animated library and for now we didn't handle more animation (but for colours) than Animated with native driver
Let you compare it: 
https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/NativeAnimatedHelper.js#L145
with our list: 
https://github.com/kmagiera/react-native-reanimated/blob/master/src/ConfigHelper.js#L6

However it does not mean that you cannot handle other animation values like  `top` or `width`, but in these cases we update them via bridge 🌉 . Specifically, it means that we're sending updating value to JS and then send it to native code, which is not supersmooth and it's only temporary solution.
But our aim is to make it better and what's more it's now under development ⛑ https://github.com/kmagiera/react-native-reanimated/pull/45
and the list of layout properties which will be handled w/o bridge will be much more longer: 
https://github.com/kmagiera/react-native-reanimated/pull/45/files#diff-b38c54b0e8fad40355c4dbd8477775bdR38.

Taking it into consideration:
1. opacity could be change fully natively right now like in Animated library
2. Other layout style's props could be changed, but it's not smooth currently
3. ...but it will be 😄
