### ISSUE TITLE
Calculate left/right window margins of zoomed in area

### ISSUE THREAD

**Issue by sanealytics** [kmagiera/react-native-reanimated#60]
Hi there,

I am new to React and got here via Expo release notes. This isn't a bug but just trying to understand the code.

I'm trying to follow the Image example as I have a similar need (map). 

I am trying to calculate the endpoints of the window as they end up after the transformations.

For example, for the sample image, if I zoom 2x with center of image, and move right by WIDTH/4,  my corners will be (B, edge, I, edge). I would like to calculate those corners so I can request the right things from the server. 

I am unable to follow the math here. Is this based on a simper example somewhere else? Or is there a trick for using the transformation matrix to get those corners?

Thanks,

![simulator screen shot - iphone 6 - 2018-08-07 at 02 25 44](https://user-images.githubusercontent.com/1840180/43758189-5572f6ce-99e9-11e8-911a-9383ecbe7e5a.png)

**Comment by sanealytics** [comment]
Hi there,

Any pointers here will be appreciated. I'm trying to make sense of this library but running into a lot of issues due to my poor lack of understanding.

How can I calculate the corners of the zoomed in section I'm in at the moment?

Thanks,

**Comment by kmagiera** [comment]
So sorry for keeping you waiting here. Ended up not having enough time today to get to this issue but hope to be able to give some pointers tomorrow

**Comment by sanealytics** [comment]
No worries.. thanks for looking into it. I really appreciate the feedback.

Here is a code sample of what I'm trying to do

https://gist.github.com/sanealytics/3425652255589dc04114d06ddb748ac5

**Comment by sanealytics** [comment]
Thanks! This is a great explanation. I will try and report back.

**Comment by sanealytics** [comment]
Unfortunately, this always finds the top-left corner of the parent image, not the top-left of the zoomed-in portion :(

I'm following your math, which is roughly reversing the transform, but I can't get it to work :(

Here is sample code to help reproduce the problem

https://gist.github.com/sanealytics/eae89a5397e6f036d5af3938b0953288

PS, nice improvement on being able to modify state in the new versions.

**Comment by sanealytics** [comment]
Closing the issue for now, changed the direction of how things are being used. Will reopen if I try this again.
