### ISSUE TITLE
Invalid prop "onHandlerStateChange" of type object

### ISSUE THREAD

**Issue by andrzey** [kmagiera/react-native-reanimated#64]
When I try out some examples I always get an error when using the iOS simulator and Expo 28.0.0 that says that `onHandlerStateChange` has an invalid prop. This happens when I copy the code from [this example](https://codedaily.io/tutorials/54/Create-a-Tap-and-Hold-Toggle-Opacity-Animated-Box-with-Reanimated-in-React-Native) and also when I watch [another tutorial](https://codedaily.io/screencasts/81/Create-a-Tap-and-Hold-Toggle-Opacity-Animated-Box-with-Reanimated-in-React-Native) one can clearly see the error in the simulator. Is this normal? Because Im really eager to learn reanimated, but when the examples dont work Im not exactly sure if there is something Im doing wrong or if the examples are wrong.

14:08:27: Warning: Failed prop type: Invalid prop `onHandlerStateChange` of type `object` supplied to `Handler`, expected `function`.
- node_modules/prop-types/checkPropTypes.js:19:20 in printWarning
- node_modules/prop-types/checkPropTypes.js:83:12 in checkPropTypes
- node_modules/react/cjs/react.development.js:1228:19 in validatePropTypes
- node_modules/react/cjs/react.development.js:1316:22 in createElementWithValidation
* App.js:76:8 in render
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:8811:23 in finishClassComponent
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:12924:25 in performUnitOfWork
- ... 16 more stack frames from framework internals

**Comment by ckknight** [comment]
https://github.com/kmagiera/react-native-gesture-handler/pull/268

**Comment by osdnk** [comment]
This issue is not related to RNR.
It's related to RNGH and fixed since 17 seconds 😄
