### ISSUE TITLE
Release of .alpha-6

### ISSUE THREAD

**Issue by rgommezz** [kmagiera/react-native-reanimated#68]
Would you guys be able to make a new alpha release?

`diffClamp` node is broken in the current one.

Also, I am not aware of the process but, how long it would take for that version to land in Expo?

The reason I ask is because I'll be imparting a workshop about animations and gestures with RN on a conference soon (12 September) and I was planning to showcase this library at the end, specially `diffClamp` for a collapsible navigation bar :)

It would be great to stick to Expo for all the examples and not having to resort to native compilation.

Let me know what you think.

Cheers!

**Comment by osdnk** [comment]
Hi @rgommezz,
Libraries in expo are being updated on each expo SDK version bump. As far as I am informed new expo SDK will be released at the beginning of September :tada: and I am confident that it will include new version of RNR and examples should be workable on with expo too.

**Comment by saleksandras** [comment]
@osdnk hi,
Really like this library!
I’m not using Expo and really want to get updated version. v10 was released 2 months ago and there was bunch of fixes since then.
Is there any chance that it will be released soon?

**Comment by osdnk** [comment]
Please expect release in very nearest future - matter of days. If you need urgently new version, you could set given branch or commit in your dependencies
