### ISSUE TITLE
interpolate does not support string values for outputRange

### ISSUE THREAD

**Issue by mldb** [kmagiera/react-native-reanimated#89]
sample code:
`this.rotate=Animated.interpolate(this.animatedValue, {
                  inputRange: [0, 1000],
                  outputRange: ['1deg', '90deg'],
                })`
error:
![image 2018-09-02 17 35 25](https://user-images.githubusercontent.com/8201960/44956267-945a9980-aed6-11e8-9ab9-a4a9dda7ea58.jpg)

**Comment by futuun** [comment]
It might be intentional because it can be achieved with `concat`
```js
Animated.concat(
    Animated.interpolate(this.animatedValue, {
        inputRange: [0, 1000],
        outputRange: [1, 90],
    }),
    'deg',
)
```

**Comment by osdnk** [comment]
Thank you for this issue. I fully agree with @futuun. In RN core it's achieved via quite a dirty way and we didn't wish to follow it

**Comment by ddereszewski** [comment]
Note, worth adding this to the docs
