### ISSUE TITLE
Make debug node logs show up for expo users

### ISSUE THREAD

**Issue by kmagiera** [kmagiera/react-native-reanimated#90]
Currently debug node logs only show up in ios console or adb logcat on Android. We should think of a solution that would make those logs available for people who use expo and does not run it from xcode

**Comment by osdnk** [comment]
Hi, @kmagiera 
I considered two ways of managing this feature:
1. Sending logs to JS in DEV mode. This feature might be useful also for number of users which use RN without AS or XCode and will no affect smoothness of release version
2. Sensing long from native side:
