### ISSUE TITLE
Matrix transform support

### ISSUE THREAD

**Issue by futuun** [kmagiera/react-native-reanimated#91]
Hey,
is there any way to use animated values from this lib inside matrix transformation?
I have few animations where I had to change transform origin and since it's not supported in react native, matrix was the least hacky way to do that, unfortunately I'm getting cryptic error:

<img width="487" alt="screenshot 2018-09-03 at 17 48 21" src="https://user-images.githubusercontent.com/15254260/44995233-75293e00-afa2-11e8-94ff-6c30916bbcf8.png">

Basic sample:
```js
import A from 'react-native-reanimated';

const deg = new A.Value(23);
const rad = A.multiply(A.divide(Math.PI, 180), deg);
const cos = A.cos(rad);
const sin = A.sin(rad);
const zAxisRotation = [
    cos, -sin, 0, 0,
    sin, cos, 0, 0,
    0, 0, 1, 0,
    0, 0, 0, 1,
];
const Sample = () => {
    return (
        <A.View
            style={{
                transform: [{
                    matrix: zAxisRotation,
                }]
            }}
        />
    );
};
```

**Comment by osdnk** [comment]
Hi @futuun,
It's not supported by our library currently. Please concern using `cond` node

**Comment by msand** [comment]
I've recently added support for useNativeDriver animation of transform styles in react-native-svg: https://github.com/react-native-community/react-native-svg/commit/fb4e877c2b23b4c52971c16d42c305d9f28a9eb5
perhaps you could get some inspiration from there, or suggest improvements to that as well.

**Comment by raffaeler** [comment]
@osdnk Are there plans for matrix support?
Support for matrix is the most essential operation needed to accumulate transformations. 
I am deeply suprised and concerned of this decision for a graphic library

**Comment by wcandillon** [comment]
I'm adding support to an `accumulatedTransform()` function in redash that solves the issue of keeping the state of a transformation into a matrix: https://github.com/wcandillon/react-native-redash/pull/224/files

It looks like matrices may never need to be exposed to React Native developers as a public API, which I find exciting :)

**Comment by raffaeler** [comment]
@wcandillon you pull request is definitely useful, but matrices are not limited to transforms.
The entire graphics world is built on matrix support and most of the graphics algorithms are based on matrices.
Not having matrices support in the codebase is like using tricycle instead of a motorbike ;-)
