### ISSUE TITLE
"card example" demo broken in react-navigation-transitioner

### ISSUE THREAD

**Issue by kmagiera** [kmagiera/react-native-reanimated#92]
Reporting here to track the progress of this issue.

Looks like the culprit could be https://github.com/kmagiera/react-native-reanimated/commit/8888b3c95fd0397fd960940940f03518dabfe5e4 since the problem surfaces in alpha.7 but not alpha.8

cc @ericvicenti

**Comment by osdnk** [comment]
@ericvicenti 
@kmagiera 
🚑
