### ISSUE TITLE
Error: Non-extensible objects are not allowed as keys

### ISSUE THREAD

**Issue by angly-cat** [kmagiera/react-native-reanimated#94]
Hi!

I'm using latest `react-native-reanimated@1.0.0-alpha.8` and `react-native-gesture-handler@1.0.7`. In some conditions I catch `Error: Non-extensible objects are not allowed as keys` (on Android emulator with API 26, don't know if reproducible on iOS or other API):

![image](https://user-images.githubusercontent.com/5000549/45203899-6cd14b80-b29f-11e8-960f-fd0ea6b0c67f.png)

The easiest way to reproduce it is to add the following code to "image viewer" example:
```
componentDidMount() {
    this.forceUpdate();
}
```
The workaround is to move `this._onPinchEvent` and `this._onPanEvent` to `render` function, thus effectively recreating them on each render.

I hope this information would help you debugging and fixing this bug. https://github.com/kmagiera/react-native-reanimated/issues/82 may be related.

**Comment by osdnk** [comment]
Fix via: https://github.com/kmagiera/react-native-reanimated/pull/95
