### ISSUE TITLE
Animated.Text color

### ISSUE THREAD

**Issue by ckknight** [kmagiera/react-native-reanimated#99]
I'd love to be wrong about this, but it appears that `Animated.Text` doesn't support `color` being an animated style.

Works, renders a white box:
```js
<Animated.View style={{ backgroundColor: Animated.color(255, 255, 255), width: 10, height: 10 }} />`
```

Doesn't work, renders black text:
```js
<Animated.Text style={{ color: Animated.color(255, 255, 255) }}>Hello!</Animated.Text>`
```

**Comment by ckknight** [comment]
Ah, this works after running `Animated.addWhitelistedNativeProps({ color: true });`

**Comment by Strate** [comment]
Looks like `backgroundColor` can not be animated for `Animated.Text` too. Can it be related to this?
